feat: update contract and unit test coverage
dashevo/dashpay-contract pull request #3
Opened 2020-08-20 23:14 UTC by Alex-Werner

2020-08-20 23:27 UTC, Alex-Werner commented
We will need to wait a little bit for some documentation update to have our contract update here. 
This should happen next week.

2020-08-21 05:46 UTC, shumkov requested changes

2020-08-21 05:46 UTC, shumkov commented on .travis.yml
> +    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)$/
We don’t need this one

2020-08-21 05:46 UTC, shumkov commented on .travis.yml
> +before_install:
I would move it to before_deploy if we don’t have it alteady in deploy script

2020-08-21 05:46 UTC, shumkov commented on package.json
> +    "@dashevo/dpp": "^0.14.0",
0.15-dev ?

2020-08-21 05:46 UTC, shumkov commented on scripts/register.js
> +async function register() {
Shouldn’t we use SDK for fetching/registration?

2020-08-21 20:20 UTC, Alex-Werner commented on .travis.yml
> +    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)$/
Borrowed from here : https://github.com/dashevo/dpns-contract/blob/v0.3-dev/.travis.yml 
Should I just get master then ?

2020-08-21 20:21 UTC, Alex-Werner commented on .travis.yml
> +before_install:
Done !

2020-08-21 20:23 UTC, Alex-Werner commented on scripts/register.js
> +async function register() {
Well, we can, but that would mean including js-dash-sdk + all it's dependencies for a slower results. 
But it is possible obviously.

2020-08-22 17:57 UTC, shumkov commented on .travis.yml
> +    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)$/
It suppose to be three options:
- master
- regexp for dev branches (0.15-dev)
- full semver regexp for tags

2020-08-22 18:01 UTC, shumkov commented on scripts/register.js
> +async function register() {
I just was thinking about the common approach for everything and a single entry point for registering contracts. If we change the logic we won’t need to update all which use low-level libraries.

2020-12-08 09:49 UTC, shumkov commented on schema/dashpay.schema.json
> +        "type": "integer"
Let's add minimum validation?

2020-12-08 09:58 UTC, shumkov commented on schema/dashpay.schema.json
> +        "minItems": 32,
```
"contentMediaType": "application/x.dash.dpp.identifier"
```

2020-12-08 09:59 UTC, Alex-Werner commented on schema/dashpay.schema.json
> +        "minItems": 32,
👍

2020-12-08 09:59 UTC, Alex-Werner commented on schema/dashpay.schema.json
> +        "type": "integer"
👍

2020-12-08 09:59 UTC, Alex-Werner commented on .travis.yml
> +    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)$/
👍

2020-12-08 10:08 UTC, shumkov approved these changes
LGTM! 👍

2020-12-08 10:10 UTC, merged